version: 1.0.{build}

skip_tags: true
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

artifacts:
- path: '*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: m49OJ7+Jdt9an3jPcTukHA==
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
